---
- name: check | checking health for apiserver
  uri:
    url: https://{{item}}:6443/healthz
    client_cert: "{{ tls_dir }}kube_apiserver.pem"
    client_key: "{{ tls_dir }}kube_apiserver-key.pem"
    return_content: yes
    status_code:
      - 200
      - 500
    validate_certs: no
  run_once: true
  delegate_to: "{{ groups['kube_apiserver'][0] }}"
  register: kube_apiserver_health
  until: " 'ok' in  kube_apiserver_health.content"
  retries: 5
  delay: 10
  loop: "{{ groups['kube_apiserver'] }}"
