---
- name: init | create ETCD user
  user:
    name: etcd
    shell: /usr/bin/false
    state: present


- name: init | unarchive ETCD binary file
  unarchive:
    src: "{{ etcd_filename }}"
    dest: /usr/bin
    mode: "0755"
    owner: "etcd"
    extra_opts:
      - --strip-components=1



- name: init | creating config dir
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - "{{ tls_dir }}"
    - "{{ etcd_data_dir }}"
    - "{{ etcd_conf }}"


# - name: init | sync TLS certificate
#   copy: 
#     src: "{{ item }}"
#     dest: "{{ tls_dir }}"
#   loop: "{{ query('fileglob', local_tls + '*pem') }}"


- name: init | sync TLS certificate
  copy: 
    src: "{{ item }}"
    dest: "{{ tls_dir }}"
  loop: 
    - "{{local_tls}}ca.pem"
    - "{{local_tls}}etcd.pem"
    - "{{local_tls}}etcd-key.pem"
