- name: create  pem  | Creating peer TLS certificate
  shell: ./cfssl gencert --ca ca.pem --ca-key ca-key.pem --config ca-config.json -profile=peer {{ item }}_peer.json | ./cfssljson --bare {{ item }}
  args: 
    chdir: /opt/ssl
  loop: "{{ peer }}"
  when: peer[0] != 0


- name: create  pem  | Creating server TLS certificate
  shell: ./cfssl gencert --ca ca.pem --ca-key ca-key.pem --config ca-config.json -profile=server {{ item }}_server.json | ./cfssljson --bare {{ item }}
  args: 
    chdir: /opt/ssl
  loop: "{{ server }}"
  when: server[0] != 0


- name: create  pem  | Creating client TLS certificate
  shell: ./cfssl gencert --ca ca.pem --ca-key ca-key.pem --config ca-config.json -profile=client {{ item }}_client.json | ./cfssljson --bare {{ item }}
  args: 
    chdir: /opt/ssl
  loop: "{{ client }}"
  when: client[0] != 0