- name: 配置kubernetes源
  template:
     src: kubernetes.repo 
     dest: /etc/yum.repos.d/kubernetes.repo

- name: 安装kubernetes-cni
  yum: 
    name: kubernetes-cni
    state: latest
    
- name: 安装kubeadm、kubelet、kubectl
  shell: "yum install -y kubeadm-{{ kubernetes_version }} kubelet-{{ kubernetes_version }} kubectl-{{ kubernetes_version }} --disableexcludes=kubernetes"
  args:
    warn: False

- name: 启动kubelet并开机启动
  service:
    name: kubelet
    state: started
    enabled: yes
