---
- name: check | checking health for controller_manager
  uri:
    url: https://{{item}}:10252/healthz
    client_cert: "{{ tls_dir }}kube_controller_manager.pem"
    client_key: "{{ tls_dir }}kube_controller_manager-key.pem"
    return_content: yes
    status_code:
      - 200
      - 500
    validate_certs: no
  run_once: true
  delegate_to: "{{ groups['kube_controller_manager'][0] }}"
  register: kube_controller_manager_health
  until: " 'ok' in  kube_controller_manager_health.content"
  retries: 5
  delay: 10
  loop: "{{ groups['kube_controller_manager'] }}"