---
- include_tasks: "init.yml"

- name: main | start kube-controller-manager
  systemd:
    name: kube-controller-manager 
    state: restarted 
    enabled: yes 
    daemon_reload: yes

- include_tasks: "check.yml"