- name: main | Create a directory if it does not exist
  file:
    path: /root/.kube/
    state: directory
    mode: '0755'
- name: main | set kubectl config
  copy:
    src: /etc/kubernetes/admin.conf 
    dest: /root/.kube/config
    mode: "0644"

