- name: main | create init file
  template:
    src: kubeadm-init.yaml.j2
    dest: /opt/kubeadm-init.yaml

- name: main | init
  shell: "/usr/bin/kubeadm init --config 
           \ /opt/kubeadm-init.yaml"
